import re

# 1. Update index.html
with open('index.html', 'r') as f:
    index_html = f.read()

# 1.1 Replace Hero CTA
primary_cta = """<a target="_blank" rel="noopener noreferrer" data-slot="button" label="Book a Free Strategy Call" style="--bg-color:#007E76;--hover-bg-color:#00766f;color:#fcfcfc" class="inline-flex shrink-0 cursor-pointer items-center justify-center bg-(--bg-color) whitespace-nowrap transition-all outline-none hover:bg-(--hover-bg-color) focus-visible:border-primary-border focus-visible:ring-[3px] focus-visible:ring-primary-interactive-bg disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-error-border aria-invalid:ring-error-interactive-bg [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 [&amp;_svg:not([class*=&#x27;size-&#x27;])]:size-4 border border-(--bg-color) hover:border-(--hover-bg-color) gap-2 px-5 py-2.5 has-[&gt;svg:first-child]:pr-4 has-[&gt;svg:last-child]:pl-4 has-[&gt;svg:only-child]:px-2.5 rounded-3xl" href="https://calendar.app.google/mCDenTF29rv4Zzb18"><span class="min-w-0 overflow-hidden text-ellipsis [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style="--typography-font-size:var(--typography-body-sm-em-font-size);--typography-font-weight:var(--typography-body-sm-em-font-weight);--typography-line-height:var(--typography-body-sm-em-line-height);--typography-letter-spacing:var(--typography-body-sm-em-letter-spacing);--typography-font-family:var(--typography-body-sm-em-font-family);color:#fcfcfc">Book a Free Strategy Call</span></a>"""
secondary_cta = """<a class="inline-flex shrink-0 cursor-pointer items-center justify-center bg-transparent whitespace-nowrap transition-all outline-none hover:bg-white/10 text-white font-medium px-5 py-2.5 rounded-3xl border border-gray-500 hover:border-white ml-0 mt-4 sm:mt-0 sm:ml-4" href="mailto:hello@clearcove.pro?subject=AI Readiness Checklist Request&body=Hi ClearCove Team,%0D%0A%0D%0AI'd like to receive the free AI Readiness Checklist to see if our operations are ready for automation.%0D%0A%0D%0AThank you!">Get AI Readiness Checklist</a>"""

# Since the hero buttons are inside an array of divs generated by Durable, we can just append the secondary CTA to the primary CTA html string
if secondary_cta not in index_html:
    index_html = index_html.replace(primary_cta, primary_cta + secondary_cta)

# 1.2 Inject Case Study
case_study_html = """
<section class="py-24 px-6 sm:px-8 bg-[var(--bg-color-alt)] text-center relative z-10" style="background-color: #0b1120;">
    <div class="max-w-4xl mx-auto">
        <p class="text-[var(--primary-color)] font-bold tracking-widest text-sm uppercase mb-4" style="color: #007E76;">Case Study: Series A FinTech</p>
        <h2 class="text-4xl md:text-5xl font-bold mb-8" style="color: #fcfcfc; line-height: 1.2;">60% Reduction in Support Costs</h2>
        <p class="text-xl leading-relaxed mb-8" style="color: #d1d5db;">
            "ClearCove automated our support intake process, reducing first-response time from 4 hours to under 2 minutes. We scaled our user base 3x without adding a single headcount."
        </p>
        <a href="https://calendar.app.google/mCDenTF29rv4Zzb18" target="_blank" class="inline-block bg-[#007E76] hover:bg-[#00665f] text-white font-medium py-3 px-8 rounded-full transition-colors">
            See how we did it
        </a>
    </div>
</section>
"""
# Find the testimonials section
testimonials_match = re.search(r'(<section[^>]*>.*?Organizations trust ClearCove.*?</section>)', index_html, re.DOTALL)
if testimonials_match and case_study_html not in index_html:
    testimonials_html = testimonials_match.group(1)
    index_html = index_html.replace(testimonials_html, case_study_html + "\n" + testimonials_html)

with open('index.html', 'w') as f:
    f.write(index_html)

# 2. Update blog.html
with open('blog.html', 'r') as f:
    blog_html = f.read()

# Replace the entire section containing the blog posts with a clean one
blog_section_match = re.search(r'(<section[^>]*>.*?Know when to hand it off.*?</section>)', blog_html, re.DOTALL)
if blog_section_match:
    new_blog_section = """
    <section class="py-24 px-6 sm:px-8 max-w-6xl mx-auto relative z-10" style="margin-top: 100px;">
        <h2 class="text-4xl font-bold mb-12" style="color: #fcfcfc; text-align: center;">Insights & Analysis</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
            <!-- Article 1 -->
            <a href="blog-support-automation.html" class="block p-8 rounded-3xl border border-gray-700/50 hover:border-gray-500 transition-colors" style="background-color: #111827;">
                <p class="text-sm uppercase tracking-wider mb-4" style="color: #9ca3af;">August 2, 2026</p>
                <h3 class="text-2xl font-bold mb-4" style="color: #fcfcfc;">Support Automation That Doesn't Feel Like a Machine</h3>
                <p class="leading-relaxed mb-6" style="color: #d1d5db;">The rush to implement AI in customer support has led to a predictable problem: terrible customer experiences. Effective AI agents are designed for resolution, not deflection.</p>
                <span style="color: #007E76; font-weight: bold;">Read more &rarr;</span>
            </a>
            
            <!-- Article 2 -->
            <a href="blog-ai-readiness.html" class="block p-8 rounded-3xl border border-gray-700/50 hover:border-gray-500 transition-colors" style="background-color: #111827;">
                <p class="text-sm uppercase tracking-wider mb-4" style="color: #9ca3af;">August 1, 2026</p>
                <h3 class="text-2xl font-bold mb-4" style="color: #fcfcfc;">5 Signs Your Business Is Ready for AI Automation</h3>
                <p class="leading-relaxed mb-6" style="color: #d1d5db;">Artificial Intelligence is no longer just for enterprise tech companies. Mid-market businesses are scaling rapidly with custom AI. Here are the 5 signs you are outgrowing manual processes.</p>
                <span style="color: #007E76; font-weight: bold;">Read more &rarr;</span>
            </a>
        </div>
    </section>
    """
    blog_html = blog_html.replace(blog_section_match.group(1), new_blog_section)
    with open('blog.html', 'w') as f:
        f.write(blog_html)

# 3. Clean up premium.js
with open('premium.js', 'r') as f:
    js = f.read()

# Remove the dynamic Case Study and CTA injections since they are now native
case_study_block = re.search(r'(// 9\. Case Study Injection.*?)(?=\s*// 10\. Secondary CTA)', js, re.DOTALL)
if case_study_block:
    js = js.replace(case_study_block.group(1), '')

cta_block = re.search(r'(// 10\. Secondary CTA.*)', js, re.DOTALL)
if cta_block:
    js = js.replace(cta_block.group(1), '')

blog_injection = re.search(r'(// 8\. Blog Page Content Injection.*?)(?=\s*// 9\. Case Study Injection|\s*// 10\. Secondary CTA|$)', js, re.DOTALL)
if blog_injection:
    js = js.replace(blog_injection.group(1), '')

with open('premium.js', 'w') as f:
    f.write(js)

print("Static HTML injections complete. premium.js cleaned up.")
